export const mockTutors = [
  {
    id: "tutor_1",
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    avatar: "/female-tutor-portrait-professional.jpg",
    bio: "Experienced math teacher with 10+ years helping students excel. Specializing in algebra, calculus, and SAT prep.",
    subjects: ["Mathematics", "Calculus", "Algebra", "SAT Prep"],
    hourlyRate: 65,
    rating: 4.9,
    reviewCount: 127,
    location: "San Francisco, CA",
    verified: true,
    responseTime: "< 1 hour",
    totalSessions: 450,
    education: [
      { degree: "M.S. Mathematics", school: "Stanford University", year: 2015 },
      { degree: "B.S. Applied Mathematics", school: "UCLA", year: 2012 },
    ],
    experience: "10+ years of teaching experience",
    availability: {
      monday: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"],
      tuesday: ["09:00", "10:00", "11:00", "14:00", "15:00"],
      wednesday: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"],
      thursday: ["14:00", "15:00", "16:00", "17:00"],
      friday: ["09:00", "10:00", "11:00"],
      saturday: [],
      sunday: [],
    },
    languages: ["English", "Spanish"],
    documents: [
      { name: "Teaching Certificate", status: "verified" },
      { name: "Background Check", status: "verified" },
      { name: "Degree Certificate", status: "verified" },
    ],
  },
  {
    id: "tutor_2",
    name: "Michael Chen",
    email: "michael.chen@email.com",
    avatar: "/male-asian-tutor-portrait-professional.jpg",
    bio: "Physics PhD with a passion for making complex concepts simple. Expert in AP Physics, mechanics, and engineering fundamentals.",
    subjects: ["Physics", "AP Physics", "Engineering", "Science"],
    hourlyRate: 75,
    rating: 4.8,
    reviewCount: 89,
    location: "Los Angeles, CA",
    verified: true,
    responseTime: "< 2 hours",
    totalSessions: 320,
    education: [
      { degree: "Ph.D. Physics", school: "MIT", year: 2018 },
      { degree: "B.S. Physics", school: "UC Berkeley", year: 2013 },
    ],
    experience: "7 years of tutoring experience",
    availability: {
      monday: ["10:00", "11:00", "15:00", "16:00", "17:00"],
      tuesday: ["10:00", "11:00", "15:00", "16:00", "17:00"],
      wednesday: ["10:00", "11:00"],
      thursday: ["10:00", "11:00", "15:00", "16:00", "17:00"],
      friday: ["10:00", "11:00", "15:00", "16:00"],
      saturday: ["10:00", "11:00", "12:00"],
      sunday: [],
    },
    languages: ["English", "Mandarin"],
    documents: [
      { name: "PhD Certificate", status: "verified" },
      { name: "Background Check", status: "verified" },
    ],
  },
  {
    id: "tutor_3",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@email.com",
    avatar: "/female-latina-tutor-portrait-professional.jpg",
    bio: "Bilingual English/Spanish tutor specializing in language arts, ESL, and creative writing. Published author and certified teacher.",
    subjects: ["English", "ESL", "Creative Writing", "Spanish"],
    hourlyRate: 55,
    rating: 4.95,
    reviewCount: 203,
    location: "Miami, FL",
    verified: true,
    responseTime: "< 30 minutes",
    totalSessions: 680,
    education: [
      { degree: "M.A. English Literature", school: "Columbia University", year: 2016 },
      { degree: "B.A. Creative Writing", school: "University of Miami", year: 2013 },
    ],
    experience: "8 years of teaching experience",
    availability: {
      monday: ["08:00", "09:00", "10:00", "13:00", "14:00", "15:00", "16:00"],
      tuesday: ["08:00", "09:00", "10:00", "13:00", "14:00", "15:00"],
      wednesday: ["08:00", "09:00", "10:00", "13:00", "14:00", "15:00", "16:00"],
      thursday: ["13:00", "14:00", "15:00", "16:00"],
      friday: ["08:00", "09:00", "10:00", "13:00", "14:00"],
      saturday: ["09:00", "10:00", "11:00"],
      sunday: ["10:00", "11:00"],
    },
    languages: ["English", "Spanish", "Portuguese"],
    documents: [
      { name: "Teaching License", status: "verified" },
      { name: "Background Check", status: "verified" },
      { name: "TESOL Certification", status: "verified" },
    ],
  },
  {
    id: "tutor_4",
    name: "David Kim",
    email: "david.kim@email.com",
    avatar: "/male-korean-tutor-portrait-professional.jpg",
    bio: "Computer Science graduate from Carnegie Mellon. Teaching programming, web development, and AP Computer Science.",
    subjects: ["Computer Science", "Programming", "Web Development", "Python"],
    hourlyRate: 80,
    rating: 4.7,
    reviewCount: 64,
    location: "Seattle, WA",
    verified: true,
    responseTime: "< 1 hour",
    totalSessions: 210,
    education: [
      { degree: "M.S. Computer Science", school: "Carnegie Mellon", year: 2019 },
      { degree: "B.S. Computer Science", school: "University of Washington", year: 2016 },
    ],
    experience: "5 years of industry + teaching experience",
    availability: {
      monday: ["17:00", "18:00", "19:00", "20:00"],
      tuesday: ["17:00", "18:00", "19:00", "20:00"],
      wednesday: ["17:00", "18:00", "19:00", "20:00"],
      thursday: ["17:00", "18:00", "19:00", "20:00"],
      friday: ["17:00", "18:00"],
      saturday: ["10:00", "11:00", "12:00", "13:00", "14:00"],
      sunday: ["10:00", "11:00", "12:00", "13:00", "14:00"],
    },
    languages: ["English", "Korean"],
    documents: [
      { name: "Degree Certificate", status: "verified" },
      { name: "Background Check", status: "pending" },
    ],
  },
  {
    id: "tutor_5",
    name: "Jessica Williams",
    email: "jessica.williams@email.com",
    avatar: "/female-african-american-tutor-portrait-professiona.jpg",
    bio: "Chemistry professor turned private tutor. Helping students conquer chemistry from basics to AP and college level.",
    subjects: ["Chemistry", "AP Chemistry", "Organic Chemistry", "Biology"],
    hourlyRate: 70,
    rating: 4.85,
    reviewCount: 156,
    location: "Chicago, IL",
    verified: true,
    responseTime: "< 2 hours",
    totalSessions: 520,
    education: [
      { degree: "Ph.D. Chemistry", school: "Northwestern University", year: 2014 },
      { degree: "B.S. Biochemistry", school: "Howard University", year: 2009 },
    ],
    experience: "12 years of teaching experience",
    availability: {
      monday: ["09:00", "10:00", "11:00", "12:00"],
      tuesday: ["09:00", "10:00", "11:00", "12:00", "15:00", "16:00"],
      wednesday: ["09:00", "10:00", "11:00", "12:00"],
      thursday: ["09:00", "10:00", "11:00", "12:00", "15:00", "16:00"],
      friday: ["09:00", "10:00", "11:00"],
      saturday: [],
      sunday: [],
    },
    languages: ["English"],
    documents: [
      { name: "PhD Certificate", status: "verified" },
      { name: "Teaching Certificate", status: "verified" },
      { name: "Background Check", status: "verified" },
    ],
  },
  {
    id: "tutor_6",
    name: "Robert Martinez",
    email: "robert.martinez@email.com",
    avatar: "/male-hispanic-tutor-portrait-professional.jpg",
    bio: "History and social studies expert with a focus on making history come alive. AP History, world history, and government.",
    subjects: ["History", "AP History", "Government", "Social Studies"],
    hourlyRate: 50,
    rating: 4.6,
    reviewCount: 78,
    location: "Austin, TX",
    verified: false,
    responseTime: "< 3 hours",
    totalSessions: 190,
    education: [
      { degree: "M.A. History", school: "UT Austin", year: 2017 },
      { degree: "B.A. Political Science", school: "Texas A&M", year: 2014 },
    ],
    experience: "6 years of teaching experience",
    availability: {
      monday: ["14:00", "15:00", "16:00", "17:00", "18:00"],
      tuesday: ["14:00", "15:00", "16:00", "17:00", "18:00"],
      wednesday: ["14:00", "15:00", "16:00", "17:00", "18:00"],
      thursday: ["14:00", "15:00", "16:00", "17:00", "18:00"],
      friday: ["14:00", "15:00", "16:00"],
      saturday: ["09:00", "10:00", "11:00", "12:00"],
      sunday: ["09:00", "10:00", "11:00", "12:00"],
    },
    languages: ["English", "Spanish"],
    documents: [
      { name: "Degree Certificate", status: "pending" },
      { name: "Background Check", status: "pending" },
    ],
  },
]

export const mockBookings = [
  {
    id: "booking_1",
    tutorId: "tutor_1",
    parentId: "parent_1",
    childId: "child_1",
    subject: "Mathematics",
    date: "2024-01-15",
    time: "14:00",
    duration: 60,
    status: "confirmed",
    price: 65,
    notes: "Focus on algebra equations",
  },
  {
    id: "booking_2",
    tutorId: "tutor_3",
    parentId: "parent_1",
    childId: "child_2",
    subject: "English",
    date: "2024-01-16",
    time: "10:00",
    duration: 60,
    status: "pending",
    price: 55,
    notes: "Essay writing practice",
  },
  {
    id: "booking_3",
    tutorId: "tutor_2",
    parentId: "parent_1",
    childId: "child_1",
    subject: "Physics",
    date: "2024-01-10",
    time: "15:00",
    duration: 90,
    status: "completed",
    price: 112.5,
    notes: "Review for upcoming test",
  },
  {
    id: "booking_4",
    tutorId: "tutor_5",
    parentId: "parent_1",
    childId: "child_1",
    subject: "Chemistry",
    date: "2024-01-18",
    time: "09:00",
    duration: 60,
    status: "confirmed",
    price: 70,
    notes: "Organic chemistry introduction",
  },
]

export const mockChildren = [
  {
    id: "child_1",
    parentId: "parent_1",
    name: "Alex Thompson",
    age: 14,
    grade: "9th Grade",
    school: "Lincoln High School",
    subjects: ["Mathematics", "Physics", "Chemistry"],
    notes: "Preparing for advanced placement tests",
    avatar: "/teenage-boy-student.jpg",
  },
  {
    id: "child_2",
    parentId: "parent_1",
    name: "Emma Thompson",
    age: 11,
    grade: "6th Grade",
    school: "Jefferson Middle School",
    subjects: ["English", "Reading", "Writing"],
    notes: "Needs help with creative writing",
    avatar: "/teenage-girl-student.jpg",
  },
]

export const mockConversations = [
  {
    id: "conv_1",
    participants: ["parent_1", "tutor_1"],
    tutorName: "Sarah Johnson",
    tutorAvatar: "/female-tutor-avatar.jpg",
    lastMessage: "Great! See you tomorrow at 2 PM.",
    lastMessageTime: "2024-01-14T10:30:00Z",
    unread: 2,
  },
  {
    id: "conv_2",
    participants: ["parent_1", "tutor_3"],
    tutorName: "Emily Rodriguez",
    tutorAvatar: "/female-latina-tutor-avatar.jpg",
    lastMessage: "I've prepared some writing exercises for Emma.",
    lastMessageTime: "2024-01-13T15:45:00Z",
    unread: 0,
  },
  {
    id: "conv_3",
    participants: ["parent_1", "tutor_2"],
    tutorName: "Michael Chen",
    tutorAvatar: "/male-asian-tutor-avatar.jpg",
    lastMessage: "The physics session went well today!",
    lastMessageTime: "2024-01-10T16:30:00Z",
    unread: 0,
  },
]

export const mockMessages = [
  {
    id: "msg_1",
    conversationId: "conv_1",
    senderId: "tutor_1",
    content: "Hi! I'm available tomorrow at 2 PM for Alex's math session. Does that work?",
    timestamp: "2024-01-14T09:00:00Z",
  },
  {
    id: "msg_2",
    conversationId: "conv_1",
    senderId: "parent_1",
    content: "Yes, that works perfectly! He's been struggling with quadratic equations.",
    timestamp: "2024-01-14T09:15:00Z",
  },
  {
    id: "msg_3",
    conversationId: "conv_1",
    senderId: "tutor_1",
    content: "No problem, I'll prepare some exercises specifically for that topic.",
    timestamp: "2024-01-14T10:00:00Z",
  },
  {
    id: "msg_4",
    conversationId: "conv_1",
    senderId: "tutor_1",
    content: "Great! See you tomorrow at 2 PM.",
    timestamp: "2024-01-14T10:30:00Z",
  },
]

export const mockReviews = [
  {
    id: "review_1",
    tutorId: "tutor_1",
    parentId: "parent_1",
    parentName: "John Thompson",
    rating: 5,
    comment: "Sarah is an amazing math tutor! My son's grades improved significantly.",
    date: "2024-01-08",
    helpful: 12,
  },
  {
    id: "review_2",
    tutorId: "tutor_1",
    parentId: "parent_2",
    parentName: "Maria Garcia",
    rating: 5,
    comment: "Very patient and explains concepts clearly. Highly recommend!",
    date: "2024-01-05",
    helpful: 8,
  },
  {
    id: "review_3",
    tutorId: "tutor_1",
    parentId: "parent_3",
    parentName: "David Lee",
    rating: 4,
    comment: "Great tutor, very knowledgeable. Sometimes sessions run a bit over time.",
    date: "2024-01-02",
    helpful: 5,
  },
]

export const mockEarnings = {
  totalEarnings: 4250,
  thisMonth: 1850,
  lastMonth: 2400,
  pending: 325,
  sessionsThisMonth: 28,
  averagePerSession: 66,
  monthlyData: [
    { month: "Aug", earnings: 1800 },
    { month: "Sep", earnings: 2100 },
    { month: "Oct", earnings: 2400 },
    { month: "Nov", earnings: 2200 },
    { month: "Dec", earnings: 2400 },
    { month: "Jan", earnings: 1850 },
  ],
}

export const mockTransactions = [
  {
    id: "trans_1",
    type: "payment",
    amount: 65,
    description: "Session with Alex Thompson - Mathematics",
    date: "2024-01-15",
    status: "completed",
  },
  {
    id: "trans_2",
    type: "payout",
    amount: 520,
    description: "Weekly payout",
    date: "2024-01-14",
    status: "completed",
  },
  {
    id: "trans_3",
    type: "payment",
    amount: 112.5,
    description: "Session with Alex Thompson - Physics",
    date: "2024-01-10",
    status: "completed",
  },
  {
    id: "trans_4",
    type: "payment",
    amount: 55,
    description: "Session with Emma Thompson - English",
    date: "2024-01-09",
    status: "pending",
  },
]

export const mockReports = [
  {
    id: "report_1",
    type: "review",
    reportedBy: "parent_4",
    reportedItem: "review_5",
    reason: "Inappropriate language",
    status: "pending",
    date: "2024-01-14",
  },
  {
    id: "report_2",
    type: "profile",
    reportedBy: "parent_5",
    reportedItem: "tutor_7",
    reason: "Misleading qualifications",
    status: "under_review",
    date: "2024-01-12",
  },
  {
    id: "report_3",
    type: "message",
    reportedBy: "tutor_2",
    reportedItem: "msg_45",
    reason: "Spam",
    status: "resolved",
    date: "2024-01-10",
  },
]

export const mockAnalytics = {
  totalUsers: 15420,
  activeTutors: 842,
  activeParents: 12350,
  totalBookings: 45230,
  revenue: 2450000,
  avgSessionRating: 4.7,
  bookingsTrend: [
    { month: "Aug", bookings: 3200 },
    { month: "Sep", bookings: 3800 },
    { month: "Oct", bookings: 4200 },
    { month: "Nov", bookings: 3900 },
    { month: "Dec", bookings: 3500 },
    { month: "Jan", bookings: 4100 },
  ],
  revenueTrend: [
    { month: "Aug", revenue: 180000 },
    { month: "Sep", revenue: 215000 },
    { month: "Oct", revenue: 240000 },
    { month: "Nov", revenue: 220000 },
    { month: "Dec", revenue: 195000 },
    { month: "Jan", revenue: 235000 },
  ],
  subjectDistribution: [
    { subject: "Mathematics", count: 12500 },
    { subject: "English", count: 9800 },
    { subject: "Science", count: 8200 },
    { subject: "Physics", count: 5400 },
    { subject: "Chemistry", count: 4200 },
    { subject: "Other", count: 5130 },
  ],
}
